
package stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccountServiceBeanService", targetNamespace = "http://services.axis2.middleware.sdu.edu.cn/", wsdlLocation = "http://localhost:8080/axis2/services/AccountServiceBeanService?wsdl")
public class AccountServiceBeanService
    extends Service
{

    private final static URL ACCOUNTSERVICEBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCOUNTSERVICEBEANSERVICE_EXCEPTION;
    private final static QName ACCOUNTSERVICEBEANSERVICE_QNAME = new QName("http://services.axis2.middleware.sdu.edu.cn/", "AccountServiceBeanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/axis2/services/AccountServiceBeanService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOUNTSERVICEBEANSERVICE_WSDL_LOCATION = url;
        ACCOUNTSERVICEBEANSERVICE_EXCEPTION = e;
    }

    public AccountServiceBeanService() {
        super(__getWsdlLocation(), ACCOUNTSERVICEBEANSERVICE_QNAME);
    }

    public AccountServiceBeanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOUNTSERVICEBEANSERVICE_QNAME, features);
    }

    public AccountServiceBeanService(URL wsdlLocation) {
        super(wsdlLocation, ACCOUNTSERVICEBEANSERVICE_QNAME);
    }

    public AccountServiceBeanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOUNTSERVICEBEANSERVICE_QNAME, features);
    }

    public AccountServiceBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountServiceBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccountServiceBean
     */
    @WebEndpoint(name = "AccountServiceBeanPort")
    public AccountServiceBean getAccountServiceBeanPort() {
        return super.getPort(new QName("http://services.axis2.middleware.sdu.edu.cn/", "AccountServiceBeanPort"), AccountServiceBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountServiceBean
     */
    @WebEndpoint(name = "AccountServiceBeanPort")
    public AccountServiceBean getAccountServiceBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.axis2.middleware.sdu.edu.cn/", "AccountServiceBeanPort"), AccountServiceBean.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOUNTSERVICEBEANSERVICE_EXCEPTION!= null) {
            throw ACCOUNTSERVICEBEANSERVICE_EXCEPTION;
        }
        return ACCOUNTSERVICEBEANSERVICE_WSDL_LOCATION;
    }

}
